---
apiversion: storage.k8s.io/v1
kind: storageClass
metadata:
  name: jenkins
  namespace: base
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain

---
apiVersion: apps/v1
kind: statefulset
metadata:
  namespace: base
  name: jenkins
  labels:
    app: jenkins
spec:
  serviceName: "jenkins"
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8smaster
      initContainers:
        - name: init-jenkins
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /var/lib/jenkins"]
          securityContext:
            privileged: true
            volumeMounts:
              - name: jenkins-data
                mountPath: /var/lib/jenkins
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - containerPort: 8080
            - containerPort: 50000
          securityContext:
            runAsUser: 1000
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/lib/jenkins
  volumeClaimTemplates:
    - metadata:
        name: jenkins-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: jenkins
        resources:
          requests:
            storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: base
spec:
  selectors:
    app: jenkins
    ports:
      - port: 8080
        targetPort: 8080
      - port: 50000
        targetPort: 50000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins
  namespace: base
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    -hosts:
      - jenkins.jnrpro.solutions
    secretName: letsencrypt-tls
  rules:
    - host: jenkins.jnrpro.solutions
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jenkins
                port:
                  number: 8080
