---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: db
data:
  DB_HOST: mysql
  DB_USER: root
  DB_NAME: prod_db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: db
  labels: 
    app: backend
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template: 
    metadata: 
      labels:
        app: backend
    spec:
      nodeSelector:
        node: app
      containers:
        - name: backend
          image: rohit7496/backend:latest
          ports:
            - containerPort: 5000
          env: 
            - name: DB_HOST
              valueFrom: 
                configMapKeyRef:
                  name: backend-configmap
                  key: DB_HOST
            - name: DB_USER
              valueFrom: 
                configMapKeyRef:
                  name: backend-configmap
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mysql_root_password
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: DB_NAME

---
apiVersion: v1
kind: Service
metadata: 
  name: backend
  namespace: db
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: db
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - dev.jnrpro.solutions
      secretName: letsencrypt-tls
  rules:
    - host: dev.jnrpro.solutions
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 5000