---
apiVersion: v1
kind: configMap
metadata:
  name: backend-configMap
  namespace: app
spec:
  data:
    DB_HOST: mysql
    DB_USER: root
    DB_NAME: 3_tier_app

---
apiVersion: v1
kind: Deployment
metadata:
  name: backend
  namespace: app
  labels: 
    app: backend
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template: 
    metdata: 
      labels:
        app: backend
  spec:
    nodeSelector:
      node=app
    containers:
      - name: backend
        image: rohit7496/backend:latest
        ports:
          - containerPort: 5000
        env: 
          - name: DB_HOST
            valueFrom: 
              configMapKeyRef:
                name: backend-configMap
                key: DB_HOST
          - name: DB_USER
            valueFrom: 
              configMapKeyRef:
                name: backend-configMap
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: mysql_root_password
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: backend-configMap
                key: DB_NAME

---
apiVersion: v1
kind: Service
metadata: 
  name: backend-svc
  namespace: app
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
