---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: db
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        node: app
      containers:
        - name: frontend
          image: 120496071282.dkr.ecr.ap-south-1.amazonaws.com/rohit_ecr:frontend-v1.0.1
          imagePullSecrets:
            - name: ecr-secret
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: db
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: db
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dev.jnrpro.solutions
      secretName: letsencrypt-prod
  rules:
    - host: dev.jnrpro.solutions
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 80
