---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: db
  labels:
    app: mysql
  type: Opaque
  data:
    db_username:  M190aWVyX2FwcA==
    db_password: Um9oaXRAMTIz
    mysql_root_password: UGFzc3dvcmRAMTIz
